config/routes.rb
Rails.application.routes.draw do
  root 'logins#index' #主页
  resources :mytests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mylogs do
    collection do
      post 'subscribe'
      post 'index'
    end
  end
  resources :tests do
    collection do
      get 'test'
    end
  end
  resources :configs #设置
  resources :devices do #设备
    resources :devicehistorylists #设备历史
    member do
      get 'refreshdevice'
    end
  end
  resources :subscribedevices do #注册设备
    collection do
      get 'getdevicesubscribeinfo'
    end
  end
  resources :devicemaps do #设备地图
    collection do
      get 'getdevice'
    end
  end
  resources :messages #短信
  resources :users do #用户
    member do
      get 'attchuser'
      get 'attchdevice'
      get 'reldevice'
    end
    resources :reldevices #关联用户设备
    resources :userdevides #用户设备
  end
  resources :getopenids do
    collection do
      get 'getopenid'
    end
  end

  post '/', to: 'ygsubscribes#create' #Iot回调接口

  resources :apis do #微信端API接口
    collection do
      get 'sign'
      get 'checkuserauth'
      get 'getuserinfo'
      get 'sendvercode'
      get 'bindphone'
      get 'changealertsms'
      get 'changealertswx'
      get 'checkdevice'
      get 'subscribedevice'
      get 'getdevicelist'
      get 'getsingledevice'
      get 'getuserdevicehisory'
      get 'binduser'
      get 'getchildrenuser'
      get 'getattchuserdetail'
      get 'getuserdevicelist'
      get 'bindattchuserdevice'
      get 'removedevice'
      get 'getdevicehistroydetail'
      get 'getcanbingdevicelist'
      get 'deletedevice'
      get 'getdevicebysn'
    end
  end
  resources :logins #登录
  resources :admins do #管理员
    collection do
      get 'checkuser'
      get 'setauth'
    end
    member do
      get 'auth'
      post 'setauth'
    end
  end
  resources :roles #管理权限
  resources :modifypwds #修改密码
  resources :noauths


end

app/models/accesstoken.rb
class Accesstoken < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :roles
end

app/models/config.rb
class Config < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
  has_and_belongs_to_many :users

  def self.checkhistroy
    devices = Device.all
    devices.each do |f|
      devicehistroys = Devicehistorylist.where('sn = ? and alarmstatus = ?',f.sn,0)
      if devicehistroys.count > 0
        devicehistroy = devicehistroys.last
        if devicehistroy.ctimestramp < Time.now + 5.minutes && devicehistroy.ctimestramp <= Time.now + 30.minutes

        end
      else
        getdevicehistroy(f.sn)

      end
    end
    Devicelog.create(sn:'')
  end

  def self.getdevicehistroy(sn)
    conn = Faraday.new(:url => Config.first.ioturl) do |faraday|
      faraday.request :url_encoded # form-encode POST params
      faraday.response :logger # log requests to STDOUT
      faraday.adapter Faraday.default_adapter # make requests with Net::HTTP
    end
    conn.headers['Authorization'] = 'Bearer ' + gettoken
    conn.params[:appId] = Config.first.appid
    conn.params[:device_id] = sn
    request = conn.post do |req|
      req.url '/api/v1/deviceDataHistory'
    end
    devicejson = JSON.parse(request.body)
    devicejson['data'].each do |f|
      if f['data']
        device =  Devicehistorylist.find_by_ctime(f['data']['time'])
        if !device
          Devicehistorylist.create(sn:f['data']['sn'],imsi:f['data']['imsi'],swver:f['data']['swver'],hwver:f['data']['hwver'],vol:f['data']['vol'],alarmstatus:f['data']['alarmstatus'],rsrp:f['data']['rsrp'],sinr:f['data']['sinr'],wsc:f['data']['wsc'],ctime:f['data']['time'],vol2:f['data']['vol2'],ctimestramp:f['timestamp'])
        end
      end
    end

    device = Device.find_by_sn(devicejson['data'].last['data']['sn'])
    if device
      device.power = devicejson['data'].last['data']['vol2']
      device.timestamp = devicejson['data'].last['timestamp']
      device.imsi = devicejson['data'].last['data']['imsi']
      device.swver = devicejson['data'].last['data']['swver']
      device.hwver = devicejson['data'].last['data']['hwver']
      if devicejson['data'].last['data']['alarmstatus'] == 1
        device.status = 1
      end
      device.save
    end
  end

  def self.gettoken#获取access_token
    access_token = ''
    access =Accesstoken.first
    if !access
      access = Accesstoken.create(access_token:'123456',exptime:'2018-01-01 0:00:00')
    end
    if Time.new < access.exptime + 60
      access_token = access.access_token
    else
      conn = Faraday.new(:url => Config.first.ioturl) do |faraday|
        faraday.request :url_encoded # form-encode POST params
        faraday.response :logger # log requests to STDOUT
        faraday.adapter Faraday.default_adapter # make requests with Net::HTTP
      end
      conn.params[:appId]= Config.first.appid
      conn.params[:secret]= Config.first.secret
      request = conn.post do |req|
        req.url '/api/v1/sec/login'
      end
      access_token = JSON.parse(request.body)['access_token']
      access.access_token=JSON.parse(request.body)['access_token']
      access.exptime = Time.now + JSON.parse(request.body)['expires_in'].to_i
      access.save

    end
    return access_token

  end


end

app/models/devicelog.rb
class Devicelog < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/mylog.rb
class Mylog < ApplicationRecord
end

app/models/mytest.rb
class Mytest < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :admins, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :childrens, class_name: "User", foreign_key: "up_id"
  belongs_to :parent, class_name: "User", foreign_key: "up_id", optional: true
  has_and_belongs_to_many :devices
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/mylogs_helper.rb
module MylogsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<script>
  $(document).ready(function(){
      var checkloginurl = '../admins/checkuser';

      if(window.location.href.indexOf("edit") > -1){
          checkloginurl = '../../admins/checkuser';
      }

      jQuery.validator.addMethod("login",function(value,element,param){
          var pattern = /^([0-9]*)+$/;
          return this.optional(element) || (!pattern.test(value));
      },"&nbsp;&nbsp;账号不能为纯数字");
      $('#validation-form').validate({
          errorElement: 'div',
          errorClass: 'help-block',
          focusInvalid: false,
          rules: {
              'admin[username]': {
                  required: true
              },
              'admin[login]': {
                  required: true,
                  login: true,
                  remote:{
                      url:checkloginurl,
                      type:'get',
                      dataType:"json"
                  }
              },
              'admin[password]': {
                  required: true
              },
              'admin[password_confirmation]': {
                  required: true,
                  equalTo: "#admin_password"
              }
          },

          messages: {
              'admin[username]': {
                  required: "&nbsp;&nbsp;姓名不能为空"
              },
              'admin[login]': {
                  required: "&nbsp;&nbsp;账号不能为空",
                  remote:'&nbsp;&nbsp;账号已存在'
              },
              'admin[password]': {
                  required: "&nbsp;&nbsp;请输入密码"
              },
              'admin[password_confirmation]': {
                  required: "&nbsp;&nbsp;请输入确认密码",
                  equalTo:'&nbsp;&nbsp;两次密码不一致'
              }
          },

          invalidHandler: function (event, validator) { //display error alert on form submit
              $('.alert-danger', $('.login-form')).show();
          },

          highlight: function (e) {
              $(e).closest('.form-group').removeClass('has-info').addClass('has-error');
          },

          success: function (e) {
              $(e).closest('.form-group').removeClass('has-error').addClass('has-info');
              $(e).remove();
          }




      });

      $('#commit').click(function(){
          if($('#statuson:checked').val()){
              $('#admin_status').val(1);
          }else{
              $('#admin_status').val(0);
          }
      });

      if(window.location.href.indexOf("edit") > -1){
          $("#admin_password").rules("remove");
          $("#admin_password_confirmation").rules("remove");
          $("#admin_login").rules("remove");
          $("#admin_password_confirmation").rules("add",{equalTo: "#admin_password",messages:{equalTo:'&nbsp;&nbsp;两次密码不一致'}});
          $('#admin_login').attr("readonly",true);
          if($('#admin_status').val() == '0'){
              $('#statusoff').attr('checked',true);
          }else{
              $('#statuson').attr('checked',true);
          }
      }

  });
</script>




<div class="row">
  <div class="col-xs-12">
    <!-- PAGE CONTENT BEGINS -->

    <%= form_with(model:admin,local:true,id:'validation-form',:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>

        <div class="form-group">
          <label class="control-label col-xs-12 col-sm-3 no-padding-right"> 姓名 </label>
          <div class="col-xs-12 col-sm-9">
            <div class="clearfix">
              <%= f.text_field :username,id: :admin_username,class:"col-xs-12 col-sm-5" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="control-label col-xs-12 col-sm-3 no-padding-right"> 账号 </label>
          <div class="col-xs-12 col-sm-9">
            <div class="clearfix">
              <%= f.text_field :login,id: :admin_login,class:"col-xs-12 col-sm-5" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="control-label col-xs-12 col-sm-3 no-padding-right"> 密码 </label>
          <div class="col-xs-12 col-sm-9">
            <div class="clearfix">
              <%= f.password_field :password,id: :admin_password,class:"col-xs-12 col-sm-5" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="control-label col-xs-12 col-sm-3 no-padding-right"> 确认密码 </label>
          <div class="col-xs-12 col-sm-9">
            <div class="clearfix">
              <%= f.password_field :password_confirmation,id: :admin_password_confirmation,class:"col-xs-12 col-sm-5" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="control-label col-xs-12 col-sm-3 no-padding-right">状态</label>

          <div class="col-xs-12 col-sm-9">
            <%= f.hidden_field :status,id: :admin_status,class:"col-xs-12 col-sm-5" %>
            <table>
              <tr>
                <td>
                  <div>
                    <label class="blue">
                      <input name="status" id="statuson" value="1" type="radio" class="ace" checked="" />
                      <span class="lbl"> 正常&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    </label>
                  </div>
                </td>
                <td>
                  <div>
                    <label class="blue">
                      <input name="status" id="statusoff" value="0" type="radio" class="ace" />
                      <span class="lbl"> 停用 </span>
                    </label>
                  </div>
                </td>
              </tr>
            </table>
          </div>
        </div>

        <div class="clearfix form-actions">
          <div class="col-md-offset-3 col-md-9">
            <button type="submit" id="commit" value="保存" class="btn btn-info" data-disable-with="保存">
              <i class="icon-ok bigger-110"></i>
              保存
            </button>
          </div>
        </div>
    <% end %>
  </div><!-- /.col -->
</div><!-- /.row -->

app/views/admins/auth.html.erb
<%= render 'layerbegin' %>

<div class="page-content">
  <div class="page-header">
    <h1>
      <%= @admin.username %>的权限
    </h1>
  </div><!-- /.page-header -->

  <script>
      $(document).ready(function(){
          $(".chosen-select").chosen();

          $(".chosen-select").val(<%= @adminroleids %>);
          $('.chosen-select').trigger('chosen:updated');
          $('#commit').click(function(){
              $('#auth').val($(".chosen-select").val());
          });
      });
  </script>




  <div class="row">
    <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->


        <%= form_tag(controller: "admins", action: "setauth") do %>
        <div class="form-group">
          <label class="control-label col-xs-12 col-sm-3 no-padding-right"> 权限组 </label>
          <div class="col-xs-12 col-sm-9">
            <div class="clearfix">
              <div class="space-2"></div>
              <select multiple="" class="width-80 chosen-select col-xs-12 col-sm-5 tag-input-style"   id="form-field-select-4" data-placeholder="请选择角色">
                <option value="">&nbsp;</option>
                <% @roles.each do |role| %>
                    <option value=<%= role.id %>><%= role.name %></option>
                <% end %>
              </select>
              <%= hidden_field_tag :auth,params[:auth],id:'auth' %>
            </div>
          </div>
        </div>
        <div class="clearfix form-actions">
          <div class="col-md-offset-3 col-md-9">
            <button type="submit" id="commit" value="保存" class="btn btn-info" data-disable-with="保存">
              <i class="icon-ok bigger-110"></i>
              保存
            </button>
          </div>
        </div>
      <% end %>


    </div><!-- /.col -->
  </div><!-- /.row -->

</div>

<%= render 'layerend' %>

app/views/admins/edit.html.erb
<%= render 'layerbegin' %>

<div class="page-content">
  <div class="page-header">
    <h1>
      编辑管理员
    </h1>
  </div><!-- /.page-header -->
<%= render 'form', admin: @admin %>

</div>

<%= render 'layerend' %>

app/views/admins/index.html.erb
<%= render 'layerbegin' %>


<style>
    .btn-transparent {
        background-color: transparent !important;
        border-color: transparent;
        color:#6fb3e0;
    }
</style>



<div class="page-content">
  <div class="page-header">
    <h1>
      管理员列表
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->

      <div class="row">
        <div class="col-xs-12">
          <div class="table-responsive">
            <table id="sample-table-1" class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th class="text-center">姓名</th>
                <th class="text-center">账号</th>
                <th class="text-center">角色组</th>
                <th class="text-center">状态</th>
                <th class="text-center">操作</th>



              </tr>
              </thead>

              <tbody>
              <% @admins.each do |admin| %>
                  <tr>
                    <td>
                      <%= admin.username %>
                    </td>
                    <td>
                      <%= admin.login %>
                    </td>

                    <td>
                      <% roles = admin.roles %>
                      <% roles.each do |role| %>
                          <span class="label"><%= role.name %></span>

                      <% end %>
                    </td>
                    <td>
                      <% if admin.status == 1 %>
                          <span class="blue">正常</span>
                      <% else %>
                          <span class="red">停用</span>
                      <% end %>
                    </td>
                    <td>
                      <div class="visible-md visible-lg hidden-sm hidden-xs btn-group" data-turbolinks="false">
                        <a class="btn btn-xs btn-warning" href=<%= edit_admin_path(admin) %>>
                          <i class="icon-edit bigger-120"></i>
                          编辑
                        </a>
                        <a class="btn btn-xs btn-primary" href=<%= auth_admin_path(admin) %>>
                          <i class="fa fa-user"></i>
                          权限
                        </a>
                        <a class="btn btn-xs btn-danger" data-confirm="Are you sure?" data-method="delete" href=<%= admin_path(admin) %>>
                          <i class="icon-trash bigger-120"></i>
                          删除
                        </a>
                      </div>

                    </td>
                  </tr>
              <% end %>








              </tbody>
            </table>
          </div><!-- /.table-responsive -->

          <div class="visible-md visible-lg btn-group pull-right" data-turbolinks="false">
            <a class="btn btn-info" href=<%= new_admin_path %>>
              <i class="fa fa-plus"></i>
              新增管理员
            </a>
          </div>

        </div><!-- /span -->
      </div><!-- /row -->

      <div data-turbolinks="false" class="text-center">
        <%= will_paginate @admins, renderer: BootstrapPagination::Rails %>
      </div>



    </div><!-- /.col -->
  </div><!-- /.row -->
</div><!-- /.page-content -->



<% render 'layerend' %>

app/views/admins/new.html.erb
<%= render 'layerbegin' %>

<div class="page-content">
  <div class="page-header">
    <h1>
      新增管理员
    </h1>
  </div><!-- /.page-header -->
<%= render 'form', admin: @admin %>
</div>

<%= render 'layerend' %>