config/routes.rb
Rails.application.routes.draw do
  root 'logins#index' #主页
  resources :mytests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mylogs do
    collection do
      post 'subscribe'
      post 'index'
    end
  end
  resources :tests do
    collection do
      get 'test'
    end
  end
  resources :configs #设置
  resources :devices do #设备
    resources :devicehistorylists #设备历史
    member do
      get 'refreshdevice'
    end
  end
  resources :subscribedevices do #注册设备
    collection do
      get 'getdevicesubscribeinfo'
    end
  end
  resources :devicemaps do #设备地图
    collection do
      get 'getdevice'
    end
  end
  resources :messages #短信
  resources :users do #用户
    member do
      get 'attchuser'
      get 'attchdevice'
      get 'reldevice'
    end
    resources :reldevices #关联用户设备
    resources :userdevides #用户设备
  end
  resources :getopenids do
    collection do
      get 'getopenid'
    end
  end

  post '/', to: 'ygsubscribes#create' #Iot回调接口

  resources :apis do #微信端API接口
    collection do
      get 'sign'
      get 'checkuserauth'
      get 'getuserinfo'
      get 'sendvercode'
      get 'bindphone'
      get 'changealertsms'
      get 'changealertswx'
      get 'checkdevice'
      get 'subscribedevice'
      get 'getdevicelist'
      get 'getsingledevice'
      get 'getuserdevicehisory'
      get 'binduser'
      get 'getchildrenuser'
      get 'getattchuserdetail'
      get 'getuserdevicelist'
      get 'bindattchuserdevice'
      get 'removedevice'
      get 'getdevicehistroydetail'
      get 'getcanbingdevicelist'
      get 'deletedevice'
      get 'getdevicebysn'
    end
  end
  resources :logins #登录
  resources :admins do #管理员
    collection do
      get 'checkuser'
      get 'setauth'
    end
    member do
      get 'auth'
      post 'setauth'
    end
  end
  resources :roles #管理权限
  resources :modifypwds #修改密码
  resources :noauths


end

app/models/accesstoken.rb
class Accesstoken < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :roles
end

app/models/config.rb
class Config < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
  has_and_belongs_to_many :users

  def self.checkhistroy
    devices = Device.all
    devices.each do |f|
      devicehistroys = Devicehistorylist.where('sn = ? and alarmstatus = ?',f.sn,0)
      if devicehistroys.count > 0
        devicehistroy = devicehistroys.last
        if devicehistroy.ctimestramp < Time.now + 5.minutes && devicehistroy.ctimestramp <= Time.now + 30.minutes

        end
      else
        getdevicehistroy(f.sn)

      end
    end
    Devicelog.create(sn:'')
  end

  def self.getdevicehistroy(sn)
    conn = Faraday.new(:url => Config.first.ioturl) do |faraday|
      faraday.request :url_encoded # form-encode POST params
      faraday.response :logger # log requests to STDOUT
      faraday.adapter Faraday.default_adapter # make requests with Net::HTTP
    end
    conn.headers['Authorization'] = 'Bearer ' + gettoken
    conn.params[:appId] = Config.first.appid
    conn.params[:device_id] = sn
    request = conn.post do |req|
      req.url '/api/v1/deviceDataHistory'
    end
    devicejson = JSON.parse(request.body)
    devicejson['data'].each do |f|
      if f['data']
        device =  Devicehistorylist.find_by_ctime(f['data']['time'])
        if !device
          Devicehistorylist.create(sn:f['data']['sn'],imsi:f['data']['imsi'],swver:f['data']['swver'],hwver:f['data']['hwver'],vol:f['data']['vol'],alarmstatus:f['data']['alarmstatus'],rsrp:f['data']['rsrp'],sinr:f['data']['sinr'],wsc:f['data']['wsc'],ctime:f['data']['time'],vol2:f['data']['vol2'],ctimestramp:f['timestamp'])
        end
      end
    end

    device = Device.find_by_sn(devicejson['data'].last['data']['sn'])
    if device
      device.power = devicejson['data'].last['data']['vol2']
      device.timestamp = devicejson['data'].last['timestamp']
      device.imsi = devicejson['data'].last['data']['imsi']
      device.swver = devicejson['data'].last['data']['swver']
      device.hwver = devicejson['data'].last['data']['hwver']
      if devicejson['data'].last['data']['alarmstatus'] == 1
        device.status = 1
      end
      device.save
    end
  end

  def self.gettoken#获取access_token
    access_token = ''
    access =Accesstoken.first
    if !access
      access = Accesstoken.create(access_token:'123456',exptime:'2018-01-01 0:00:00')
    end
    if Time.new < access.exptime + 60
      access_token = access.access_token
    else
      conn = Faraday.new(:url => Config.first.ioturl) do |faraday|
        faraday.request :url_encoded # form-encode POST params
        faraday.response :logger # log requests to STDOUT
        faraday.adapter Faraday.default_adapter # make requests with Net::HTTP
      end
      conn.params[:appId]= Config.first.appid
      conn.params[:secret]= Config.first.secret
      request = conn.post do |req|
        req.url '/api/v1/sec/login'
      end
      access_token = JSON.parse(request.body)['access_token']
      access.access_token=JSON.parse(request.body)['access_token']
      access.exptime = Time.now + JSON.parse(request.body)['expires_in'].to_i
      access.save

    end
    return access_token

  end


end

app/models/devicelog.rb
class Devicelog < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/mylog.rb
class Mylog < ApplicationRecord
end

app/models/mytest.rb
class Mytest < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :admins, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :childrens, class_name: "User", foreign_key: "up_id"
  belongs_to :parent, class_name: "User", foreign_key: "up_id", optional: true
  has_and_belongs_to_many :devices
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def index

  end

  def create
    @status = ''

    admin = Admin.find_by(login:params[:login][:login])
    if verify_rucaptcha?(admin)
      if admin && admin.authenticate(params[:login][:password])
        if admin.status == 0
          @status = "用户已停用，请联系管理员！"
        else
          session[:userid] = admin.id
          session[:username] = admin.username
          redirect_to devices_path
        end
      else
        @status = "用户名或密码无效！"
      end
    else
      @status = "验证码无效！"

    end

  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/mylogs_helper.rb
module MylogsHelper
end

app/helpers/mytests_helper.rb
module MytestsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/logins/create.js.erb
var src = $('#rucapimg').attr('src');
$('#rucapimg').attr('src',src);

$('#messagediv').show();
$('#messagespan').text('<%= @status %>');

app/views/logins/index.html.erb
<style>



    .form{
        align-items: center;
        background: rgba(255,255,255,0.4);
        padding: 20px;
        padding-left: 80px;
        padding-right: 80px;
        border-radius: 5px;
    }

</style>

<script>
    $(document).ready(function(){
        $('#rucapimg').click(function(){
            var src = this.src;
            this.src=src;
        });
    });

</script>



<div class="container position-relative login-box visible widget-box no-border" style="margin-top: 200px;">

  <%= form_for(:login, url: logins_path,remote: true,:html => {:class=>'col-sm-offset-6 col-sm-6  form form-horizontal'}) do |f| %>

      <h3 class="text-center">用户登录</h3>

      <div class="col-md-12">
        <label class="block clearfix">
      <span class="block input-icon ">

        <%= f.text_field :login ,class:"form-control",placeholder:"用户名"%>
        <i class="icon-user"></i>
      </span>
        </label>
      </div>

      <div class="col-md-12">
        <label class="block clearfix">
    	<span class="block input-icon ">

          <%= f.password_field :password ,class:"form-control",placeholder:"密码" %>
          <i class="icon-lock"></i>
		</span>
        </label>
      </div>
      <div class="col-md-12">
        <label class="block clearfix">
    	<span class="block input-icon">
<table width="100%">
  <tr>
    <td width="70%">
      <%= rucaptcha_input_tag(class: 'form-control', placeholder: '输入验证码') %>
    </td>
    <td width="30%" align="right">
      <%= rucaptcha_image_tag('height':'35',id:'rucapimg') %>
    </td>
  </tr>

</table>
		</span>



        </label>

        <div class="alert alert-danger" id="messagediv" style="display: none;">
          <strong>
            <i class="icon-warning-sign"></i>
          </strong>
          <span id="messagespan"></span>
          <br />
        </div>
      </div>

      &nbsp;<br/>
      <div class="col-md-12 " data-turbolinks="false">
        <!--<a href="#"><span>忘记密码</span></a>-->
        <button type="submit" class="width-35 pull-right btn btn-sm btn-primary">登录</button>
      </div>

  <% end %>



</div>