config/routes.rb
Rails.application.routes.draw do
  root 'logins#index' #主页
  resources :mytests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mylogs do
    collection do
      post 'subscribe'
      post 'index'
    end
  end
  resources :tests do
    collection do
      get 'test'
    end
  end
  resources :configs #设置
  resources :devices do #设备
    resources :devicehistorylists #设备历史
    member do
      get 'refreshdevice'
    end
  end
  resources :subscribedevices do #注册设备
    collection do
      get 'getdevicesubscribeinfo'
    end
  end
  resources :devicemaps do #设备地图
    collection do
      get 'getdevice'
    end
  end
  resources :messages #短信
  resources :users do #用户
    member do
      get 'attchuser'
      get 'attchdevice'
      get 'reldevice'
    end
    resources :reldevices #关联用户设备
    resources :userdevides #用户设备
  end
  resources :getopenids do
    collection do
      get 'getopenid'
    end
  end

  post '/', to: 'ygsubscribes#create' #Iot回调接口

  resources :apis do #微信端API接口
    collection do
      get 'sign'
      get 'checkuserauth'
      get 'getuserinfo'
      get 'sendvercode'
      get 'bindphone'
      get 'changealertsms'
      get 'changealertswx'
      get 'checkdevice'
      get 'subscribedevice'
      get 'getdevicelist'
      get 'getsingledevice'
      get 'getuserdevicehisory'
      get 'binduser'
      get 'getchildrenuser'
      get 'getattchuserdetail'
      get 'getuserdevicelist'
      get 'bindattchuserdevice'
      get 'removedevice'
      get 'getdevicehistroydetail'
      get 'getcanbingdevicelist'
      get 'deletedevice'
      get 'getdevicebysn'
    end
  end
  resources :logins #登录
  resources :admins do #管理员
    collection do
      get 'checkuser'
      get 'setauth'
    end
    member do
      get 'auth'
      post 'setauth'
    end
  end
  resources :roles #管理权限
  resources :modifypwds #修改密码
  resources :noauths


end

app/models/accesstoken.rb
class Accesstoken < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :roles
end

app/models/config.rb
class Config < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
  has_and_belongs_to_many :users

  def self.checkhistroy
    devices = Device.all
    devices.each do |f|
      devicehistroys = Devicehistorylist.where('sn = ? and alarmstatus = ?',f.sn,0)
      if devicehistroys.count > 0
        devicehistroy = devicehistroys.last
        if devicehistroy.ctimestramp < Time.now + 5.minutes && devicehistroy.ctimestramp <= Time.now + 30.minutes

        end
      else
        getdevicehistroy(f.sn)

      end
    end
    Devicelog.create(sn:'')
  end

  def self.getdevicehistroy(sn)
    conn = Faraday.new(:url => Config.first.ioturl) do |faraday|
      faraday.request :url_encoded # form-encode POST params
      faraday.response :logger # log requests to STDOUT
      faraday.adapter Faraday.default_adapter # make requests with Net::HTTP
    end
    conn.headers['Authorization'] = 'Bearer ' + gettoken
    conn.params[:appId] = Config.first.appid
    conn.params[:device_id] = sn
    request = conn.post do |req|
      req.url '/api/v1/deviceDataHistory'
    end
    devicejson = JSON.parse(request.body)
    devicejson['data'].each do |f|
      if f['data']
        device =  Devicehistorylist.find_by_ctime(f['data']['time'])
        if !device
          Devicehistorylist.create(sn:f['data']['sn'],imsi:f['data']['imsi'],swver:f['data']['swver'],hwver:f['data']['hwver'],vol:f['data']['vol'],alarmstatus:f['data']['alarmstatus'],rsrp:f['data']['rsrp'],sinr:f['data']['sinr'],wsc:f['data']['wsc'],ctime:f['data']['time'],vol2:f['data']['vol2'],ctimestramp:f['timestamp'])
        end
      end
    end

    device = Device.find_by_sn(devicejson['data'].last['data']['sn'])
    if device
      device.power = devicejson['data'].last['data']['vol2']
      device.timestamp = devicejson['data'].last['timestamp']
      device.imsi = devicejson['data'].last['data']['imsi']
      device.swver = devicejson['data'].last['data']['swver']
      device.hwver = devicejson['data'].last['data']['hwver']
      if devicejson['data'].last['data']['alarmstatus'] == 1
        device.status = 1
      end
      device.save
    end
  end

  def self.gettoken#获取access_token
    access_token = ''
    access =Accesstoken.first
    if !access
      access = Accesstoken.create(access_token:'123456',exptime:'2018-01-01 0:00:00')
    end
    if Time.new < access.exptime + 60
      access_token = access.access_token
    else
      conn = Faraday.new(:url => Config.first.ioturl) do |faraday|
        faraday.request :url_encoded # form-encode POST params
        faraday.response :logger # log requests to STDOUT
        faraday.adapter Faraday.default_adapter # make requests with Net::HTTP
      end
      conn.params[:appId]= Config.first.appid
      conn.params[:secret]= Config.first.secret
      request = conn.post do |req|
        req.url '/api/v1/sec/login'
      end
      access_token = JSON.parse(request.body)['access_token']
      access.access_token=JSON.parse(request.body)['access_token']
      access.exptime = Time.now + JSON.parse(request.body)['expires_in'].to_i
      access.save

    end
    return access_token

  end


end

app/models/devicelog.rb
class Devicelog < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/mylog.rb
class Mylog < ApplicationRecord
end

app/models/mytest.rb
class Mytest < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :admins, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :childrens, class_name: "User", foreign_key: "up_id"
  belongs_to :parent, class_name: "User", foreign_key: "up_id", optional: true
  has_and_belongs_to_many :devices
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action {checkauth 'user_user'}
  before_action :set_user, only: [:show, :edit, :update, :destroy, :refreshdevice]
  def index
    @users = User.all.order('id desc').paginate(:page => params[:page], :per_page => 15)
  end

  def edit

  end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(device_params)
    respond_to do |format|
      if @device.save
        #getdevicehisory(@device.sn)
        format.html { redirect_to devices_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to edit_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  def show

  end

  def attchuser
    @currentuser = User.find(params[:id])
    @attchusers = @currentuser.childrens
  end

  def attchdevice
    @devices = User.find(params[:id]).devices.paginate(:page => params[:page], :per_page => 15)
  end

  def reldevice
    @user = User.find(params[:id])
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:openid, :headurl, :phone, :sex, :status, :up_id, :device_id, :nickname)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/mylogs_helper.rb
module MylogsHelper
end

app/helpers/mytests_helper.rb
module MytestsHelper
end

app/helpers/noauths_helper.rb
module NoauthsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/attchdevice.html.erb
<%= render 'layerbegin' %>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=iOxsL9Z27dKiNtY5s4m8vRjUyZiNwZOC"></script>
<script>
    $(document).ready(function(){
        var map = new BMap.Map("allmap");
        map.centerAndZoom('昆明',18);
        map.enableScrollWheelZoom();
        map.enableContinuousZoom();
        $('.coorbtn').click(function(){
            $('#coorval').val($(this).val());
            $('#my-modal').modal('show');

        });

        $('#my-modal').on('shown.bs.modal', function () {
            map.clearOverlays();
            var pointX = $('#coorval').val().split(',')[0];
            var pointY = $('#coorval').val().split(',')[1];
            map.centerAndZoom(new BMap.Point(pointX, pointY),18);
            var marker = new BMap.Marker(new BMap.Point(pointX, pointY));
            map.addOverlay(marker);
        })

    });
</script>

<style>
    .btn-transparent {
        background-color: transparent !important;
        border-color: transparent;
        color:#6fb3e0;
    }
</style>



<div class="page-content">
  <div class="page-header">
    <h1>
      设备列表
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->

      <div class="row">
        <div class="col-xs-12">
          <div class="table-responsive">
            <table id="sample-table-1" class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th class="text-center">设备SN</th>
                <th class="text-center">设备名称</th>
                <th class="text-center">型号</th>
                <th class="text-center">地址</th>
                <th class="text-center">坐标位置</th>
                <th class="text-center">所在楼层</th>
                <th class="text-center">imsi</th>
                <th class="text-center">swver</th>
                <th class="text-center">hwver</th>
                <th class="text-center">电量</th>
                <th class="text-center">最后上报</th>
                <th class="text-center">状态</th>
                <th class="text-center">操作</th>
              </tr>
              </thead>

              <tbody>
              <% @devices.each do |device| %>
                  <tr>
                    <td>
                      <%= device.sn %>
                    </td>
                    <td>
                      <%= device.name %>
                    </td>
                    <td>
                      <%= device.model %>
                    </td>
                    <td>
                      <%= device.address %>
                    </td>
                    <td>
                      <%= device.coordinate %>
                      <button class="btn btn-info btn-xs pull-right coorbtn" value=<%= device.coordinate %>>
                        <i class="fa fa-map-marker"></i>
                      </button>
                    </td>
                    <td>
                      <%= device.floor %>
                    </td>
                    <td>
                      <%= device.imsi %>
                    </td>
                    <td>
                      <%= device.swver %>
                    </td>
                    <td>
                      <%= device.hwver %>
                    </td>
                    <td>
                      <%= device.power %>
                    </td>
                    <td>
                      <% if device.timestamp %>
                          <%= device.timestamp.strftime('%Y-%m-%d %H:%M:%S') %>
                      <% end %>
                    </td>
                    <td>
                      <% if device.status.to_s == '0' || device.status.to_s == '' %>
                      <span class="text-success">
                        正常
                      </span>
                      <% else %>
                          <span class="text-danger">
                        异常
                      </span>
                      <% end %>
                    </td>
                    <td>
                      <a class="btn btn-xs btn-danger" data-confirm="确认将此设备解绑?" data-method="delete" href=<%= user_userdevide_path(device) %>>
                        <i class="icon-trash bigger-120"></i>
                        解绑
                      </a>
                    </td>

                  </tr>
              <% end %>








              </tbody>
            </table>
            <a class="btn btn-primary pull-right" href=<%= new_user_reldevice_path(params[:id]) %>>
              关联设备
            </a>
          </div><!-- /.table-responsive -->
        </div><!-- /span -->
      </div><!-- /row -->

      <div data-turbolinks="false" class="text-center">
        <%= will_paginate @devices, renderer: BootstrapPagination::Rails %>
      </div>

      <div id="my-modal" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h3 class="smaller lighter blue no-margin">坐标位置</h3><input id="coorval" class="pull-right" style="margin-top: -22px;display: none;">
            </div>

            <div class="modal-body">
              <div id="allmap" style="width: 540px;height: 600px;"></div>
            </div>

            <div class="modal-footer">
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div>


    </div><!-- /.col -->
  </div><!-- /.row -->
</div><!-- /.page-content -->



<% render 'layerend' %>

app/views/users/attchuser.html.erb
<%= render 'layerbegin' %>
<div class="page-content">
  <div class="page-header">
    <h1>
      <%= @currentuser.phone %> 附属用户
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->

      <div class="row">
        <div class="col-xs-12">
          <div class="table-responsive">
            <table id="sample-table-1" class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th class="text-center">昵称</th>
                <th class="text-center">openid</th>
                <th class="text-center"></th>
                <th class="text-center">手机</th>
                <th class="text-center">性别</th>
                <th class="text-center">状态</th>
                <th class="text-center">附属用户</th>
              </tr>
              </thead>

              <tbody>
              <% @attchusers.each do |user| %>
                  <tr>
                    <td>
                      <%= user.nickname %>
                    </td>
                    <td>
                      <%= user.openid %>
                    </td>
                    <td>
                      <img src=<%= user.headurl %> width='40'>

                    </td>
                    <td>
                      <%= user.phone %>
                    </td>
                    <td>

                      <% if user.sex == 1%>
                          男
                      <% else %>
                          女
                      <% end %>
                    </td>
                    <td>
                      <% if user.status == 1%>
                                            <span class="text-success">
                        正常
                      </span>
                      <% else %>
                                                                  <span class="text-danger">
                        停用
                      </span>
                      <% end %>

                    </td>
                    <td>
                      <a  href=<%= attchuser_user_path(user) %>>
                        <%= user.childrens.count %>
                      </a>

                    </td>

                  </tr>
              <% end %>








              </tbody>
            </table>
          </div><!-- /.table-responsive -->
        </div><!-- /span -->
      </div><!-- /row -->






    </div><!-- /.col -->
  </div><!-- /.row -->
</div><!-- /.page-content -->



<% render 'layerend' %>

app/views/users/index.html.erb
<%= render 'layerbegin' %>
<div class="page-content">
  <div class="page-header">
    <h1>
      用户
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->

      <div class="row">
        <div class="col-xs-12">
          <div class="table-responsive">
            <table id="sample-table-1" class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th class="text-center">昵称</th>
                <th class="text-center">openid</th>
                <th class="text-center"></th>
                <th class="text-center">手机</th>
                <th class="text-center">性别</th>
                <th class="text-center">状态</th>
                <th class="text-center">附属用户</th>
                <th class="text-center">关联设备</th>




              </tr>
              </thead>

              <tbody>
              <% @users.each do |user| %>
                  <tr>
                    <td>
                      <%= user.nickname %>
                    </td>
                    <td>
                      <%= user.openid %>
                    </td>
                    <td class="text-center">
                      <img src=<%= user.headurl %> width='40'>
                    </td>
                    <td>
                      <%= user.phone %>
                    </td>
                    <td>
                      <% if user.sex == 1%>
                          男
                      <% elsif user.sex ==2 %>
                          女
                      <% end %>
                    </td>
                    <td>

                      <% if user.status == 1%>
                      <span class="text-success">
                        正常
                      </span>
                      <% else %>
                      <span class="text-danger">
                        停用
                      </span>
                      <% end %>

                    </td>
                    <td>
                      <%= link_to user.childrens.count,attchuser_user_path(user),class:'btn btn-primary btn-xs' %>
                    </td>
                    <td>
                      <%= link_to user.devices.count,attchdevice_user_path(user),class:'btn btn-primary btn-xs' %>
                    </td>
                  </tr>
              <% end %>








              </tbody>
            </table>
          </div><!-- /.table-responsive -->
        </div><!-- /span -->
      </div><!-- /row -->

      <div data-turbolinks="false" class="text-center">
        <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
      </div>




    </div><!-- /.col -->
  </div><!-- /.row -->
</div><!-- /.page-content -->



<% render 'layerend' %>

app/views/users/reldevice.html.erb
<%= render 'layerbegin' %>
<div class="page-content">
  <div class="page-header">
    <h1>
      关联设备
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->

      <%= form_for([@user, @user.devices.build],:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
          <h3 class="header smaller lighter blue">
            <small></small>
          </h3>
          <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 设备SN </label>
            <div class="col-sm-9">
              <%= f.text_field :sn,class:"col-xs-10 col-sm-5",id:'sn' %>
              <span  class="help-inline col-xs-12 col-sm-7" >
												<span id="snalert" class="middle text-danger" style="display: none;"></span>
											</span>
            </div>
          </div>



          <div class="clearfix form-actions">
            <div class="col-md-offset-3 col-md-9">
              <button type="submit" name="commit" value="保存" class="btn btn-info" data-disable-with="保存" id="submit">
                <i class="icon-ok bigger-110"></i>
                保存
              </button>
            </div>
          </div>
      <% end %>




    </div><!-- /.col -->
  </div><!-- /.row -->
</div><!-- /.page-content -->



<% render 'layerend' %>